---
- name: reading unseal key contents
  delegate_to: localhost
  become: no
  command: "cat {{ item }}"
  register: _vault_unseal_keys
  with_fileglob: "{{ vault_unseal_keys_dir }}/*"

- name: unseal vault with unseal keys
  no_log: yes
  command: "vault operator unseal {{ item.stdout }}"
  environment:
    VAULT_ADDR: "http://10.0.0.184:8200"
  with_items: "{{ _vault_unseal_keys.results }}"